### ISSUE TITLE
Overflow on phones

### ISSUE THREAD

**Issue by nenadalm** [svimanet/blockit#1]
Hi. Cool app. It doesn't work well on phones though. I use Chrome on Android and I can't see right part of the board. It can be also reproduced on desktop with Chrome and mobile device simulation (https://developer.chrome.com/docs/devtools/device-mode#open_the_device_toolbar). See screenshot:

![20241005_10h00m58_grim](https://github.com/user-attachments/assets/fb1ce8d1-54ef-48bb-8262-6bdfe5a754aa)

It works on Android Chrome if I toggle "Desktop site" (except the scrore text is quite small).

**Comment by svimanet** [comment]
Hi, thanks for letting me know! I'll add it to my list of TODOs, but will probably not fix it immediately. A bit tired of this project atm. I could add the TODOs to the README if there is any contributor interest.

Just out of curiosity; how and why did you stumble upon this project?

**Comment by nenadalm** [comment]
I'm interested in pwas (can be run on desktops, phones... one app to run everywhere), wrote a few little ones myself. I also like phone games to pass time if I have nothing to do for short periods of time. So time to time I look for recent updates on repos tagged `pwa` and `game`: https://github.com/search?q=topic%3Apwa+topic%3Agame&type=repositories&s=updated&o=desc . I like yours and shared it with one more person who has better score than I do so far...

Note that there are also pwa directories where you can add your pwa, such as:
- https://paquet.app/home (my favourite - opensource - you send json with info about your pwa and if you change anything - icon, description, ... it gets automatically updated)
- https://www.pwalist.app/ (closed source, you fill a form with details about your pwa and you have to update it via their form if anything about your app updates)

**Comment by svimanet** [comment]
Thank you very much for sharing! 
I'll consider throwing this up on paquet and pwalist when I eventually find energy to polish it.

My SOs score record is 482 btw, I have not been able to beat it yet (mine is 318).

**Comment by nenadalm** [comment]
My SO has 352 and I've had ~250.
