### ISSUE TITLE
Highscore sorting 

### ISSUE THREAD

**Issue by nenadalm** [svimanet/blockit#5]
Thanks for the highcore feature. Now I don't have to make screenshots to remember the score to brag with (456). 

I usually just care about my highest score. Would you consider sorting the table by highest to lowest score? Or naybe have some option to sort it by table heading user clicked at if you prefer sorting by date?

**Comment by svimanet** [comment]
@nenadalm Pushed a feature yesterday that solves the problem of easily viewing the highest score, but nothing more. The score header is now a button that sorts by highest score, descending. 

I have not added features for (ascending score sort), (date sort (ascending and descending)), and (reset sort).

**Comment by nenadalm** [comment]
Thanks, works great!
